[sections]
badges = ""
table_of_contents = ""
features = ""
project_tree = ""
requirements = ""
deployment = ""
main_modules = ""
recommended_modules = ""
installation = ""
configuration = ""
troubleshooting_faq = ""
maintainers = ""
license = ""
contributions = ""
examples = ""
testing = ""

[section_emojis]
table_of_contents = ":bookmark_tabs:"
features = ":sparkles:"
project_tree = ":file_folder:"
requirements = ":hammer_and_wrench:"
deployment = ":rocket:"
main_modules = ":package:"
recommended_modules = ":jigsaw:"
installation = ":arrow_down:"
configuration = ":gear:"
troubleshooting_faq = ":question:"
maintainers = ":woman_office_worker: :man_office_worker:"
license = ":lock_with_ink_pen:"
contributions = ":handshake:"
examples = ":clipboard:"
testing = ":test_tube:"

[license_badges]
MIT = "![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)"
GPL_3_0 = "![License: GPL v3](https://img.shields.io/badge/License-GPLv3-blue.svg)"
Apache_2_0 = "![License](https://img.shields.io/badge/License-Apache%202.0-blue.svg)"
MPL_2_0 = "![License: MPL 2.0](https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg)"
AGPL_3_0 = "![License: AGPL v3](https://img.shields.io/badge/License-AGPL%20v3-blue.svg)"
